# -*- coding: utf-8 -*-
"""CropDisease.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xq5FgkP1hkoh8chgEOW4fEheu85_4gtX
"""

!unzip /content/Crop-Disease-Detection-master.zip -d "/content/drive/MyDrive/Colab Notebooks"



def warn(*args, **kwargs):
	pass
	import warnings
	warnings.warn = warn


import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import img_to_array
from PIL import Image
import numpy as np
import pickle

list1 = ['Pepper__bell___Bacterial_spot', 'Pepper__bell___healthy',
 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy',
 'Tomato_Bacterial_spot' ,'Tomato_Early_blight' ,'Tomato_Late_blight',
 'Tomato_Leaf_Mold', 'Tomato_Septoria_leaf_spot',
 'Tomato_Spider_mites_Two_spotted_spider_mite' ,'Tomato__Target_Spot',
 'Tomato__Tomato_YellowLeaf__Curl_Virus','c',
 'Tomato_healthy']


image = Image.open("/content/drive/MyDrive/Colab Notebooks/Crop-Disease-Detection-master/tomatoDisease.jpg")
image =image.resize(tuple((64, 64)),Image.ANTIALIAS)
imagearray=img_to_array(image)
imagearray = np.expand_dims(imagearray,axis =0)

# tf.logging.set_verbosity(tf.logging.ERROR)

# model=pickle.load(open('model.pkl','rb'))
model = load_model("/content/drive/MyDrive/Colab Notebooks/Crop-Disease-Detection-master/my_model.h5")
INIT_LR= 0.001
opt=Adam(lr=INIT_LR)#, decay=INIT_LR / EPOCHS)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=["accuracy"])
prediction = model.predict(imagearray)

# prediction=model.predict(imagearray)
# lb=pickle.load(open('label_transform.pkl','rb'))

k=0
for i in range(15):
    val = prediction.item(i)
    if val==1:
        k = i
        list1[k]
        break

print(list1[k])



